
package gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.security.InvalidParameterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author gekoncze
 */
public class MainWindow extends javax.swing.JFrame {

    public MainWindow() {
        initComponents();
        
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent ke) {
                super.keyPressed(ke);
                gamePanel.requestFocus();
                gamePanel.keyPressedEvent(ke.getKeyCode());
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                super.keyReleased(ke);
                gamePanel.requestFocus();
                gamePanel.keyReleasedEvent(ke.getKeyCode());
            }
        });
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent we) {
                super.windowClosed(we);
                gamePanel.cleanup();
                ServerDialog.destroy();
                ClientDialog.destroy();
            }
        });
        
        setLocationRelativeTo(null);
        try {
            setIconImage(ImageIO.read(getClass().getResource("icon.png")));
        } catch (IOException | IllegalArgumentException e) {
            System.out.println("Could not load icon.");
        }
        setTitle("Tennis 4x4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePanel = new gui.GamePanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonClient = new javax.swing.JButton();
        jButtonServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 4, 4));

        jButtonClient.setText("Client");
        jButtonClient.setFocusable(false);
        jButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClient);

        jButtonServer.setText("Server");
        jButtonServer.setFocusable(false);
        jButtonServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonServer);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientActionPerformed
        ClientDialog.create(this);
        ClientDialog.ssetVisible(true);
    }//GEN-LAST:event_jButtonClientActionPerformed

    private void jButtonServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServerActionPerformed
        ServerDialog.create(this);
        ServerDialog.ssetVisible(true);
    }//GEN-LAST:event_jButtonServerActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.GamePanel gamePanel;
    private javax.swing.JButton jButtonClient;
    private javax.swing.JButton jButtonServer;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
